import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  concepts: [{type: 'autogenerated', dirName: 'concepts'}],
  works: [{type: 'autogenerated', dirName: 'works'}],
};

export default sidebars;
